name: typo3-toolbox
type: typo3
docroot: public
php_version: "8.4"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "11.4"
webimage_extra_packages: [libxml2-utils]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
