name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Install dependencies
        run: |
          ddev start
          ddev composer install
          ddev npm i

      - name: Composer audit
        run: ddev composer audit

      - name: Run static code analysis
        run: |
          ddev composer lint
          ddev npm run lint

      - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        name: Annotate PHP CS Fixer
        with:
          files: php-cs-fixer.xml
          notices-as-warnings: true

      - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        name: Annotate PHPStan
        with:
          files: phpstan.xml
          notices-as-warnings: true
